# Generated by Django 2.2.5 on 2019-09-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='tarih',
            field=models.DateTimeField(auto_now=True, verbose_name='tarih'),
        ),
    ]
