# Generated by Django 2.2.5 on 2019-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0002_yazi_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tarih'),
        ),
    ]
