# Generated by Django 2.2.5 on 2019-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0003_auto_20190920_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='baglanti',
            field=models.CharField(default='default baglanti', max_length=15),
            preserve_default=False,
        ),
    ]
