# Generated by Django 2.2.5 on 2019-09-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0004_yazi_baglanti'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='kategori',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
