# Generated by Django 2.2.5 on 2019-09-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0006_auto_20190924_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='icerik',
            field=models.TextField(max_length=500),
        ),
    ]
