# Generated by Django 2.2.5 on 2019-09-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0007_auto_20190924_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='kategori',
            field=models.CharField(choices=[('K', 'Kose Yazisi'), ('A', 'Analiz'), ('Y', 'Yazili Tarih'), ('M', 'Makale')], max_length=1),
        ),
    ]
