# Generated by Django 2.2.5 on 2019-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0008_auto_20190924_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='icerik',
            field=models.TextField(),
        ),
    ]
