# Generated by Django 2.2.5 on 2019-10-08 01:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0009_auto_20190927_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='icerik2',
            field=tinymce.models.HTMLField(default='asdficerikasdf'),
            preserve_default=False,
        ),
    ]
