# Generated by Django 2.2.5 on 2019-10-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0010_yazi_icerik2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazi',
            name='icerik2',
        ),
        migrations.AddField(
            model_name='yazi',
            name='fotograf',
            field=models.ImageField(default='#', upload_to='images/'),
            preserve_default=False,
        ),
    ]
