# Generated by Django 2.2.5 on 2019-10-08 01:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0011_auto_20191008_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='icerik2',
            field=ckeditor.fields.RichTextField(default='icerik22222'),
            preserve_default=False,
        ),
    ]
