# Generated by Django 2.2.5 on 2019-10-08 02:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0012_yazi_icerik2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='icerik2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
